name: Run Upload Script

on:
  schedule:
    - cron: "0 * * * *"   # Runs at the start of every hour
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ vars.SSH_HOST }}
      SSH_USER: ${{ vars.SSH_USER }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      SSH_KEY: ${{ vars.SSH_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # or your version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run Python Script
        run: |
          python upload_to_sheets.py
