
[gcp_service_account]
type='service_account'
project_id= 'bobtail-dashboard-123'
private_key_id='3cfdad943c0cde5ffe63fb7254eb11e99e80d0a1'
client_email= 'bobtail-dashboard@bobtail-dashboard-123.iam.gserviceaccount.com'
client_id= '110770844380010408889'
auth_uri= 'https://accounts.google.com/o/oauth2/auth'
token_uri= 'https://oauth2.googleapis.com/token'
auth_provider_x509_cert_url= 'https://www.googleapis.com/oauth2/v1/certs'
client_x509_cert_url= 'https://www.googleapis.com/robot/v1/metadata/x509/bobtail-dashboard%40bobtail-dashboard-123.iam.gserviceaccount.com'
universe_domain= 'googleapis.com'
private_key= """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC79YA2yK/GWGd5
wkwMUYTN6gdTOPt1Mh/Qpgo0GclTv0L6DCyZFjnYkCLPuBdn+E1rvrNXt8kil9W7
Rn/Zaot80knADuxrr8hmsl0BNBXGpKrcQaYIbDygxZqUYZqWCBbdAFQiOyMChvuQ
cjX2kPtOv+6A8l4Fk/IpgRq+2t96NZGpYibORpjjHLd1slOJo/MDLKJvMhySjYFl
rqv1BpVYzsPN+ylJ/gfZ9O/H4CYxrGwIsMtKKDuwOHa5+a1JKJ1unjRzPTeVBvPg
80iWBxISX0/OUIT85AJITSN8zPVi+IlOWs7udvAz/5HSM85MeRYouQmQhtmFH0VA
yNL+svghAgMBAAECgf9ZId94G0zZW9+2EQcyadxdYzdJP++Yo/k/K+R3nVx1WnEC
IsPQO1OZkloi88NY8QCSsULBVjMLmvUmc66TnvLtPmVUe1jVUe0dLKtUgF6gB9z+
liMmQcdLQzakWgsn53rwH2r5nXf8utL3eZgdiDzXtPmYkvBptL7uiUq/Nwv2TdQf
dk9VfFFdvW/cfrSFMj961wnYfDo85ddUga3xITTJ3Udnce/1aPsTrFZlNH6DKVtD
B89k/H0yQZduOQyhOoA66gdUA1Q4TxBNPEUCk5cRUvW/ijoEc2C4rHPiuTRTypC3
jHXeRwKqoqJ4Jpz7IcT7PmMZyKrF2Vb0dD3usEECgYEA3FtC7ZxVrMYt2OLWNWEd
cQGhFY3yTIp32c42G/xBeJdzBjagHqCjw6kS1oSg1WyWPKjXicM7+GCT9geeFmw0
4tNQVt4scZkZuJuqBm9yCKt4ZVcZqPEWodUHFmS1M5NjlnatWg9ay0I8vC4f8O93
XHHsFd+8A/AoSAxEwy31NpkCgYEA2lyxFBb1c85dyDfn/1a0H5QgmVoHkO6D/E3G
kLaJVXET5scsWfEpDMJFmcA0lURWJTQDs1iJ0eXmUh8jVB28oFWvKkA07Esine/i
abLtLmwk2rVsDXr673stpQI2Wsw3jCE+KcPT3Bm7B5usXN/dI1VZdbSmNdTTUzuy
4d+mKskCgYEAyZ//p2bKxeI4BSHZmtIXnFU/TXeqYvq4G2UiAY1ZYrxBFUhaTmvy
LI/BmuOUPnSzKyHaxkUL1IKaIB5sOlwcMAfmlPWJeQ/7hv14H5dNoj0zVpbR9dF
QhSn/Yd8fYq5Lu28RJGUJDOhWxZhR5X1g3MB8Cnd4USXtwTyzhx5KNECgYBv27PK
eshZ/okEG794ic3Tr2nTpM7ja4upH55sW1WWs0pimf0aRfOlWY+V52QIYu1OOYr7
wIs5Pu/xeYn7eRA7giktF58EvKiLB2uQgdwGP9fRQcaMUUdijlMfiDaX5K0/13ek
pXBN+9BXYWO2X+dERmCBb30FbnSi2p4UHyFcIQKBgQC6BvrYR97xUGG+X0tqzuWX
oye0WEiF7RcxkR111gNua6IV7wyPazZLenrJ1WAbpdKQdJixxqUsZhud4bX66EAc
GdK+jjpVe6zGOyjKn23Ed8CPgu6iSlV5H2cpRvoR49e0T0uC7ZqcVz7khNAR9+Mi\nPGGHnFxC+vAG4/Jp9TGmlQ==
-----END PRIVATE KEY-----
"""
